// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP04Bg9Ap1V1Q3McUNrtdzuM7f8A7-lJQ',
    appId: '1:828790561797:web:1c0882c97a17d0b9ac506c',
    messagingSenderId: '828790561797',
    projectId: 'travel-app-8c892',
    authDomain: 'travel-app-8c892.firebaseapp.com',
    storageBucket: 'travel-app-8c892.appspot.com',
    measurementId: 'G-HTQ7826HKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvYX51HeTDth5wmYVRZirj-bl1N0NjJ8',
    appId: '1:828790561797:android:2e2998e38a2bbf03ac506c',
    messagingSenderId: '828790561797',
    projectId: 'travel-app-8c892',
    storageBucket: 'travel-app-8c892.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBObu9OYquYp8LesCItzrSef2jpno42pls',
    appId: '1:828790561797:ios:9ffe19da6a8bf93dac506c',
    messagingSenderId: '828790561797',
    projectId: 'travel-app-8c892',
    storageBucket: 'travel-app-8c892.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBObu9OYquYp8LesCItzrSef2jpno42pls',
    appId: '1:828790561797:ios:f2cf3742f6f83f85ac506c',
    messagingSenderId: '828790561797',
    projectId: 'travel-app-8c892',
    storageBucket: 'travel-app-8c892.appspot.com',
    iosBundleId: 'com.example.travelApp.RunnerTests',
  );
}
